version: "3.7"
services: 
  flux-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 8080:8080
    tty: true
    environment: 
      HOST: 0.0.0.0
      PORT: 8080
    volumes: 
      - ./:/app
      - /app/node_modules