apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: flux-web
  name: flux-web
spec:
  selector:
    matchLabels:
      app: flux-web
  template:
    metadata:
      labels:
        app: flux-web
    spec:
      containers:
      - env:
        ##READ_ONLY = String
        # default value false
        - name: READ_ONLY
          value: ""
        - name: NAMESPACES
          value: namespace-a;namespace-b;namespace-c
        - name: FLUX_URL
          value: http://flux-api:3030
        - name: DEFAULT_NAMESPACE
          value: yadata-stg
        image: idobry/flux-web:0.1.79
        imagePullPolicy: IfNotPresent
        name: flux-web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
