apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: flux-web
  name: flux-web
spec:
  selector:
    matchLabels:
      app: flux-web
  template:
    metadata:
      labels:
        app: flux-web
    spec:
      containers:
      - env:
        - name: NAMESPACES
          value: namespace-a;namespace-b;namespace-c
        - name: FLUX_URL
          value: http://flux-api
        - name: DEFAULT_NAMESPACE
          value: yadata-stg
        image: idobry/flux-web
        imagePullPolicy: IfNotPresent
        name: flux-web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
