apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flux-web.fullname" . }}-backend
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
{{ include "flux-web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flux-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flux-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          env:
{{ toYaml .Values.backend.env | indent 11 }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
