apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "flux-web.fullname" . }}-rbac-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]