apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux-web.fullname" . }}-rbac-binding
subjects:
- kind: ServiceAccount
  name: default
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: {{ include "flux-web.fullname" . }}-rbac-clusterrole
  apiGroup: rbac.authorization.k8s.io