apiVersion: v1
kind: Service
metadata:
  name: {{ include "flux-web.fullname" . }}-frontend
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
{{ include "flux-web.labels" . | indent 4 }}
  {{- if .Values.frontend.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.frontend.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end -}}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "flux-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
